<?php

namespace Ais\DosenBundle\Repository;

/**
 * DosenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DosenRepository extends \Doctrine\ORM\EntityRepository
{
}
